# aggiornamento incrementale
#incremental: true
# aggiunta per prova 31/01/21
#permalink: /:slug/
breadcrumbs: true  # disabled by default
kramdown:
    auto_ids: true

sass:
    sass_dir: assets/scss/
    style: compressed
    # Exclude from processing.
    exclude:
      - bower_components
#finale
# Site settings 
# SEO START
vers: "1.0.36"
title: "" # BACKEND
tagline: ""  # BACKEND
email: "" # BACKEND
description: ""  # BACKEND
keywords: ""  # BACKEND
baseurl: "" #"/614c8b47bf2d200019128ae4-614c8b75c7b4000023a22beb" # the subpath of your site, e.g. /it x localizzare il sito
# Google Search Console
google_site_verification: ""
# Google Analytics Console
google_analytics: ""
locale: en #- The locale these tags are marked up in. Of the format # BACKEND
language_TERRITORY:  #Default is en_US. Takes priority over existing config key 
# lang:
## SEO CONFIGURAZIONE
## Theme Options SEO
animated_header: "false"  #true 
#twitter_username: tiledesk #ATTENTO DA MODIFICARE IN PRODUZIONE
#github_username:  tiledesk #ATTENTO DA MODIFICARE IN PRODUZIONE
img_width: 32
img_height: 32
img_url: /assets/images/favicon.png #ATTENTO CONTROLLLA

#twitter: #DA STUDIARE NON FUNZIONA
#  username: tildesk_prova
#  card: summary_large_image
#logo: "/images/uploads/logo-deep-linking-tiledesk.png" 
cover_image: "" # Image will Display in Social Media When share the website
width: ""
height: "" 
fb:app_id: "" #"1233942360457519"
#social: # DA STUDIARE
#  name: TiledeskCANC
#  links:
#    - https://twitter.com/tiledesk
#    - https://www.facebook.com/tiledesk
#    - https://www.linkedin.com/it/tiledesk
#    - https://github.com/tiledesk


toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-


# SEO END
#facebook: "https://www.facebook.com"
#twitter: "https://www.twitter.com"
#instagram: "https://www.instagram.com"
#github: "https://www.github.com"
#linkedin: "https://www.linkedin.com"
#behance: "https://www.behance.com"
#reddit: "https://www.reddit.com"
#vimeo: "https://www.vimeo.com"
#dribble: "https://www.dribble.com"
# youtube: "https://www.youtube.com"

## TIMEZONE
timezone: Europe/Rome # ATTENTO PERMETTERE IL CAMBIAMENTO IN PRODUZIONE

# Build settings
markdown: kramdown
theme: minima
url: "https://help.tiledesk.com" # the base hostname & protocol for your site # BACKEND
production: true
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

collections:
  team_members:
    output: false
    permalink: /team_members/:path/
  testimonials:
    output: false
    permalink: /testimonials/:path/
  docs:
    output: false
    permalink: /docs/:title/
  posts:
    output: true
    #permalink: /help-center/:categories/:year/:month/:day/:title:output_ext
    #permalink: /help-center/:slugified_categories/:title/
    #permalink: /help-center/:categories/:title/
    permalink: /articles/:title/
    #permalink: /:categories/:title/ # INSERISCE LA CATEGORIA NELL'URL
    #permalink: /:categories/:path
  # Archives
  #archives:
    #output: true
    #permalink: /archives/:path/


############################################################
# Site configuration for the Jekyll Pagination Gem
# The values here represent the defaults if nothing is set
#paginate: 2
#paginate_path: "/blog/page:num/"
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 2

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: 'funzionality'

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  #locale: 'es_ES' # BACKEND
  locale: 'en_EN' # BACKEND

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################
# JEKYLL-ARCHIVES
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
year_archive:
  type: jekyll-archives
  path: /archives/

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive-taxonomy
    tag: archive-tag
    year: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    year: /archives/year/:year/
  
  # Defaults
  defaults:
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: false
  - scope:
      path:            "*.*"
    values:
      sitemap:         false
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      image: /assets/images/topics-bg.jpg

# JEKYLL-ARCHIVES FINE
autopages:
  enabled: false #DISABILITA LA CREAZIONE AUTOMATICA DELLE PAGINE TAG, CATEGORY ..
 
# Tag Options

permalink: /:title/ 
feed:
  collections:
    posts:
      path: "/index.xml"
